ordercloud-api/ngx-shopper

- src/UI/Buyer/src/app/order/components/payment-list/payment-list.component.html
- src/UI/Buyer/src/app/order/containers/order-detail/order-detail.component.html
- src/UI/Buyer/src/app/order/containers/order-shipments/order-shipments.component.html
html wasn't binding to correct values which caused page to freeze
Fixes #39 
- [ x] I have updated the acceptance criteria on the task so that it can be tested
> fix: Order detail not loading #39

- src/UI/Buyer/src/app/layout/header/header.component.html
- src/UI/Buyer/src/app/layout/header/header.component.scss
- src/UI/Buyer/src/app/shared/services/oc-line-item/oc-line-item.service.ts
- Display item count on cart badge
- Dont allow multiple line items with same productID. If a line item with a productID already exists then merge quantity with previous and use one line item
- no unit tests on this one but i have created a task specifically to address unit tests for line item service as a whole
Fixes #47 
> fix: Cart icon #47

- LICENSE.txt
- README.md
- package-lock.json
- src/UI/Buyer/src/app/auth/containers/login/login.component.html
- src/UI/Buyer/src/app/auth/containers/login/login.component.spec.ts
- src/UI/Buyer/src/app/auth/containers/login/login.component.ts
- src/UI/Buyer/src/app/layout/header/header.component.html
- src/UI/Buyer/src/app/layout/header/header.component.scss
- src/UI/Buyer/src/app/order/components/payment-list/payment-list.component.html
- src/UI/Buyer/src/app/order/containers/order-detail/order-detail.component.html
- src/UI/Buyer/src/app/order/containers/order-shipments/order-shipments.component.html
- src/UI/Buyer/src/app/products/containers/product-list/product-list.component.html
- src/UI/Buyer/src/app/products/containers/product-list/product-list.component.spec.ts
- src/UI/Buyer/src/app/products/containers/product-list/product-list.component.ts
- src/UI/Buyer/src/app/products/models/product-sort-strats.enum.ts
- src/UI/Buyer/src/app/shared/pipes/map-to-iterable/map-to-iterable.pipe.ts
- src/UI/Buyer/src/app/shared/services/oc-line-item/oc-line-item.service.ts
- src/UI/Buyer/src/app/shared/shared.module.ts
- License added
- Readme added with simple instructions for getting started locally
- Don't link to registration unless anon
- Fix line item count on cart icon (wasn't visible)
- Sort products server-side via the api
- misc bugs where html not binding to correct value, causing site to freeze
> Update master - bug fixes and readme 

- src/UI/Buyer/src/app/order/components/order-list/order-list.component.html
- src/UI/Buyer/src/app/order/components/order-list/order-list.component.spec.ts
- src/UI/Buyer/src/app/order/components/order-list/order-list.component.ts
- src/UI/Buyer/src/app/order/containers/order-detail/order-detail.component.html
- src/UI/Buyer/src/app/order/containers/order-history/order-history.component.html
- src/UI/Buyer/src/app/order/containers/order-history/order-history.component.spec.ts
- src/UI/Buyer/src/app/order/containers/order-history/order-history.component.ts
- src/UI/Buyer/src/app/products/containers/product-list/product-list.component.ts
- src/UI/Buyer/src/app/shared/services/app-state/app-state.service.ts
- src/UI/Buyer/src/app/shared/services/authorize-net/authorize-net.service.ts
- Added ability to filter orders by favorite orders in the order history section.
- Also a minor refactor of all the functions that add query params in OrderHistory and ProductList.
- Unit tests passing
Fixes # (issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] Refactor (change/optimize code without changing external behavior)
> Favorite orders

- src/UI/Buyer/src/app/auth/containers/login/login.component.html
- src/UI/Buyer/src/app/auth/containers/login/login.component.spec.ts
- src/UI/Buyer/src/app/auth/containers/login/login.component.ts
- src/UI/Buyer/src/app/shared/guards/has-token/has-token.guard.spec.ts
- src/UI/Buyer/src/app/shared/guards/has-token/has-token.guard.ts
- Don't show link to register if anonymous shopping is disabled. 
- Remember me feature fully working.
Fixes #43 
#40  
> Clean up two Auth bugs.

- src/UI/Buyer/angular.json
- src/UI/Buyer/package.json
- src/UI/Buyer/src/app/auth/containers/forgot-password/forgot-password.component.spec.ts
- src/UI/Buyer/src/app/auth/containers/forgot-password/forgot-password.component.ts
- src/UI/Buyer/src/app/config/app.config.ts
- src/UI/Buyer/src/environments/environment.production.ts
- src/UI/Buyer/src/environments/environment.ts
- get rid of local environment configuration
- dynamically retrieve base url
- [x ] Refactor (change/optimize code without changing external behavior)
> update app configs

- src/UI/Buyer/src/app/products/components/additional-image-gallery/additional-image-gallery.component.html
- src/UI/Buyer/src/app/products/components/additional-image-gallery/additional-image-gallery.component.spec.ts
- src/UI/Buyer/src/app/products/components/additional-image-gallery/additional-image-gallery.component.ts
- src/UI/Buyer/src/app/products/containers/product-details/product-details.component.html
- src/UI/Buyer/src/app/products/containers/product-details/product-details.component.spec.ts
- src/UI/Buyer/src/app/products/containers/product-details/product-details.component.ts
- src/UI/Buyer/src/app/shared/components/line-item-card/line-item-card.component.html
- src/UI/Buyer/src/app/shared/components/product-card/product-card.component.html
- Removing unused nav breadcrumbs
- Small UI improvements
- removing hard-coded image urls.
Fixes #45
- [ x] Refactor (change/optimize code without changing external behavior)
- [ x] I have updated the acceptance criteria on the task so that it can be tested
> Product details page

- src/UI/Buyer/package.json
update build script to target production configuration
- [x ] Refactor (change/optimize code without changing external behavior)
> target production configuration on build

- src/UI/Buyer/src/app/order/components/date-filter/date-filter.component.spec.ts
- src/UI/Buyer/src/app/order/components/date-filter/date-filter.component.ts
- src/UI/Buyer/src/app/products/containers/product-details/product-details.component.html
- src/UI/Buyer/src/app/products/containers/product-details/product-details.component.spec.ts
- src/UI/Buyer/src/app/products/containers/product-details/product-details.component.ts
- src/UI/Buyer/src/app/shared/components/quantity-input/quantity-input.component.html
- src/UI/Buyer/src/app/shared/components/quantity-input/quantity-input.component.spec.ts
- src/UI/Buyer/src/app/shared/components/quantity-input/quantity-input.component.ts
- Also gets rid of endless loop of ngOnInit in cart.
> Fixing two bugs. Filter orders by date and quantity input in cart.

- src/UI/Buyer/src/app/order/components/date-filter/date-filter.component.spec.ts
- src/UI/Buyer/src/app/order/components/date-filter/date-filter.component.ts
- src/UI/Buyer/src/app/products/containers/product-details/product-details.component.html
- src/UI/Buyer/src/app/products/containers/product-details/product-details.component.spec.ts
- src/UI/Buyer/src/app/products/containers/product-details/product-details.component.ts
- src/UI/Buyer/src/app/shared/components/quantity-input/quantity-input.component.html
- src/UI/Buyer/src/app/shared/components/quantity-input/quantity-input.component.spec.ts
- src/UI/Buyer/src/app/shared/components/quantity-input/quantity-input.component.ts
- Summary of the change and which issue is fixed. 
- Relevant motivation and context. 
- List any dependencies that are required for this change.
- Reference to related issues
Fixes # (issue)
> Quantity input bug

- docs/PULL_REQUEST_TEMPLATE.md
> Change PR template so issues aren't closed by PR's

- src/UI/Buyer/src/app/app.component.html
- src/UI/Buyer/src/app/app.component.ts
- src/UI/Buyer/src/app/auth/services/app-auth.service.spec.ts
- src/UI/Buyer/src/app/auth/services/app-auth.service.ts
- src/UI/Buyer/src/app/shared/guards/has-token/has-token.guard.spec.ts
- src/UI/Buyer/src/app/shared/guards/has-token/has-token.guard.ts
- src/UI/Buyer/src/app/shared/services/app-state/app-state.service.ts
- src/UI/package-lock.json
- src/UI/package.json
fixed but where the homepage was visible for a split second to users before the were correctly routed to login page
there were also some npm warnings around security vulnerabilities that were addressed by updating karma version. Keeping a close eye on this issue - https://github.com/karma-runner/karma/issues/2994 which should close out the rest of the warnings we see
Fixes # 112
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] I have performed a self-review of my own code
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] I have updated the acceptance criteria on the task so that it can be tested
> fix: homepage flicker when not logged in and some security warnings

- src/UI/Buyer/src/app/checkout/components/checkout-confirm/checkout-confirm.component.html
- src/UI/Buyer/src/app/checkout/components/checkout-confirm/checkout-confirm.component.spec.ts
- src/UI/Buyer/src/app/checkout/components/checkout-confirm/checkout-confirm.component.ts
- src/UI/Buyer/src/app/checkout/containers/checkout-address/checkout-address.component.html
- src/UI/Buyer/src/app/checkout/containers/checkout-address/checkout-address.component.spec.ts
- src/UI/Buyer/src/app/checkout/containers/checkout-address/checkout-address.component.ts
- src/UI/Buyer/src/app/order/containers/order-approval/order-approval.component.html
- src/UI/Buyer/src/app/order/containers/order-detail/order-detail.component.html
- src/UI/Buyer/src/app/order/containers/order-history/order-history.component.html
- src/UI/Buyer/src/app/profile/containers/address-list/address-list.component.html
- src/UI/Buyer/src/app/shared/components/generic-browse/generic-browse.component.html
- src/UI/Buyer/src/app/shared/components/modal/modal.component.spec.ts
- src/UI/Buyer/src/app/shared/components/modal/modal.component.ts
- src/UI/Buyer/src/app/shared/services/modal/modal.service.ts
- Issues with Modal and Addresses in checkout section
For Reference #69 #99 #111
- [x ] Bug fix (non-breaking change which fixes an issue)
> Checkout Address Issues

- docs/PULL_REQUEST_TEMPLATE.md
- src/UI/Buyer/src/app/order/containers/order-reorder/order-reorder.component.html
- src/UI/Buyer/src/app/order/containers/order-reorder/order-reorder.component.spec.ts
- src/UI/Buyer/src/app/order/containers/order-reorder/order-reorder.component.ts
- src/UI/Buyer/src/app/order/containers/order/order.component.html
- src/UI/Buyer/src/app/order/order.module.ts
- src/UI/Buyer/src/app/shared/index.ts
- src/UI/Buyer/src/app/shared/services/oc-reorder/oc-reorder.interface.ts
- src/UI/Buyer/src/app/shared/services/oc-reorder/oc-reorder.service.spec.ts
- src/UI/Buyer/src/app/shared/services/oc-reorder/oc-reorder.service.ts
- src/UI/Buyer/src/app/shared/shared.module.ts
* merge fix
* remove /src/UI/Buyer/.gitIgnore
* remove karma.conf.js
* remove package-lock.json
* remove package.json
* remove readme
* these files were moved
* Feat: Reorder an Order
This is a container component which takes in a order id. validate the line items on the order, then display which items that are invalid and an add to cart button. Use Container because it calls out to the lineItemService to create line items with the valid products.
* Update reorder component to work with breaking changes
Unit test the order-reorder container
* refactor app lineitem service
* updated asked for changes
* Add Unit tests
update the service to throw an error if no idea is there.
- Summary of the change and which issue is fixed.
- Relevant motivation and context.
- List any dependencies that are …
> ReOrder ability (#118)

- src/UI/Buyer/src/app/layout/home/home.component.html
- src/UI/Buyer/src/app/order/components/order-list/order-list.component.html
- src/UI/Buyer/src/app/products/containers/product-list/product-list.component.html
- src/UI/Buyer/src/app/shared/components/generic-browse/generic-browse.component.html
- src/UI/Seller/src/app/product-management/containers/product-table/product-table.component.html
- src/UI/Seller/src/app/user-management/container/user-table/user-table.component.html
- only show carousel slides, announcements and featured products if the data is defined
- limit number of pages in pagination bar to 10
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] New and existing unit tests pass locally with my changes
> bug fixes noticed when building with new seller org

- src/UI/Buyer/src/app/config/app.config.ts
remove roles that aren't needed by buyer, i think these were a holdover from winmark
- [ x] Refactor (change/optimize code without changing external behavior)
> remove extraneous roles from buyer app

- src/UI/Buyer/src/app/order/containers/order-history/order-history.component.spec.ts
- src/UI/Buyer/src/app/shared/components/search/search.component.spec.ts
- src/UI/Buyer/src/app/shared/components/search/search.component.ts
it could be confusing for a user to see text in search bar but results not reflecting that
For Reference #164 
> clear search bar if products are no longer filtered by search term

- src/UI/Buyer/src/app/shared/components/line-item-card/line-item-card.component.html
- src/UI/Buyer/src/app/shared/components/lineitem-list-wrapper/lineitem-list-wrapper.component.html
IE doesn't like flex :( 
For Reference #154 
> fix: display bug in cart where line items take too much vertical space

- src/UI/Buyer/src/app/layout/footer/footer.component.html
- src/UI/Buyer/src/app/layout/header/header.component.html
- src/UI/Buyer/src/app/layout/header/header.component.ts
- src/UI/Buyer/src/app/layout/main/main.component.scss
- src/UI/Buyer/src/app/shared/components/lineitem-list-wrapper/lineitem-list-wrapper.component.html
- src/UI/Buyer/src/app/shared/components/search/search.component.spec.ts
- src/UI/Buyer/src/app/shared/components/search/search.component.ts
- src/UI/Buyer/src/app/shared/services/line-item/line-item.service.ts
- src/UI/Buyer/src/styles/_shame.scss
> fixes: search bug, popover on add to cart, and cart display bug

- src/UI/Buyer/src/app/auth/containers/login/login.component.html
- src/UI/Seller/src/app/shared/components/address-form/address-form.component.spec.ts
- src/UI/Seller/src/app/shared/components/address-form/address-form.component.ts
- src/UI/Seller/src/app/shared/components/user-form/user-form.component.html
- src/UI/Seller/src/app/shared/components/user-form/user-form.component.spec.ts
- src/UI/Seller/src/app/shared/components/user-form/user-form.component.ts
- src/UI/Seller/src/app/shared/containers/address-table/address-table.component.html
- src/UI/Seller/src/app/shared/containers/address-table/address-table.component.spec.ts
- src/UI/Seller/src/app/shared/containers/address-table/address-table.component.ts
- src/UI/Seller/src/app/shared/containers/user-table/user-table.component.html
- src/UI/Seller/src/app/shared/containers/user-table/user-table.component.spec.ts
- src/UI/Seller/src/app/shared/containers/user-table/user-table.component.ts
For Reference #185, #209
- [x ] I have added tests that prove my fix is effective or that my feature works
> Seller Bug with updating ID's + Remove password field.

- README.md
- docs/PULL_REQUEST_TEMPLATE.md
- src/UI/Buyer/README.md
updates to PR template and README's
- [ x] This change requires a documentation update
- [ x] I have made corresponding changes to the documentation
> chore: update pr template and README's (main and buyer)

- src/UI/Buyer/src/app/shared/directives/fallback-image/fallback-image.directive.ts
the default optional parameters i was setting diddn't seem to be working so no fallback image was getting set
> fix fallback image directive

- src/UI/Buyer/src/app/shared/services/line-item/line-item.service.ts
noticed this on winmark
For Reference # (issue)
> fix: unable to add line items on anon shopping

- src/UI/Buyer/src/app/shared/components/address-form/address-form.component.spec.ts
- src/UI/Buyer/src/app/shared/services/favorites/favorites.service.spec.ts
- src/UI/Buyer/src/app/shared/services/favorites/favorites.service.ts
Limit number of Favorite orders and products to preserve space in user.xp
For Reference #169
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have added tests that prove my fix is effective or that my feature works
> Limit number of favorites.

- src/UI/Seller/src/app/config/app.config.ts
- src/UI/Seller/src/app/shared/containers/category-table/category-table.component.spec.ts
- src/UI/Seller/src/app/shared/containers/category-table/category-table.component.ts
Bug fix. Category to user group assignments don't show up right away.
For Reference #231, #230 
- [x ] I have commented my code, particularly in hard-to-understand areas
> Category to UserGroup Assignments now update automatically.

- src/UI/Buyer/src/app/product/containers/product-list/product-list.component.html
Issues was cause by duplicate ids.
For Reference #213
> toggle favorites in IE bug

- src/UI/Buyer/src/app/profile/containers/address-list/address-list.component.html
- src/UI/Buyer/src/app/profile/containers/address-list/address-list.component.spec.ts
- src/UI/Buyer/src/app/profile/containers/address-list/address-list.component.ts
- src/UI/Buyer/src/app/shared/components/address-form/address-form.component.html
- src/UI/Buyer/src/app/shared/components/address-form/address-form.component.spec.ts
- src/UI/Buyer/src/app/shared/components/address-form/address-form.component.ts
- src/UI/Buyer/src/app/shared/containers/register/register.component.spec.ts
- src/UI/Buyer/src/app/shared/containers/register/register.component.ts
- src/UI/Buyer/src/app/shared/services/favorites/favorites.service.spec.ts
- src/UI/Buyer/src/app/shared/services/favorites/favorites.service.ts
- src/UI/Buyer/src/app/shared/services/form-error/form-error.service.spec.ts
- src/UI/Buyer/src/app/shared/services/form-error/form-error.service.ts
- src/UI/Buyer/src/app/shared/validators/zip-code/zip-code.validator.spec.ts
- src/UI/Buyer/src/app/shared/validators/zip-code/zip-code.validator.ts
- src/UI/Seller/src/app/shared/components/address-form/address-form.component.html
- src/UI/Seller/src/app/shared/components/address-form/address-form.component.spec.ts
- src/UI/Seller/src/app/shared/components/address-form/address-form.component.ts
- src/UI/Seller/src/app/shared/services/form-error/form-error.service.ts
- src/UI/Seller/src/app/shared/validators/zip-code/zip-code.validator.spec.ts
- src/UI/Seller/src/app/shared/validators/zip-code/zip-code.validator.ts
Three bug fixes. 
- Zip code validation on addresses
- "Are you sure" prompt on delete address
- Limit number of favorites off by one
For Reference #121, #159, #254
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have added tests that prove my fix is effective or that my feature works
> Squashing bugs

- src/UI/Buyer/src/app/checkout/containers/checkout/checkout.component.ts
data wasn't being used or set anywhere
- [ x] Refactor (change/optimize code without changing external behavior)
> remove unused payments list call in confirm

- src/UI/Buyer/src/app/auth/services/app-auth.service.spec.ts
- src/UI/Buyer/src/app/auth/services/app-auth.service.ts
- src/UI/Buyer/src/app/config/error-handling.config.ts
- src/UI/Seller/src/app/auth/services/app-auth.service.spec.ts
- src/UI/Seller/src/app/auth/services/app-auth.service.ts
- src/UI/Seller/src/app/config/error-handling.config.ts
Users should now see "Your session has expired. Please log in."
- [ x] I have verified my contribution works and looks well in Firefox, Safari and Internet Explorer
> display a user friendly error message when their session has expired

- src/UI/Buyer/src/app/checkout/containers/checkout/checkout.component.spec.ts
- src/UI/Buyer/src/app/checkout/containers/checkout/checkout.component.ts
- src/UI/Buyer/src/app/config/error-handling.config.ts
On submit get order to double check that it has not already been submitted. If it has throw an error and prevent checkout.
For Reference #293 
- [ x] I have made corresponding changes to the documentation
- [ x] I have updated the acceptance criteria on the task so that it can be tested
- [ x] I have verified my contribution works and looks well in Firefox, Safari and Internet Explorer
> Prevent resubmit 293

- src/UI/Buyer/src/app/product/containers/product-details/product-details.component.html
- src/UI/Buyer/src/app/product/containers/product-details/product-details.component.spec.ts
- src/UI/Buyer/src/app/product/containers/product-details/product-details.component.ts
- src/UI/Buyer/src/app/product/containers/product-list/product-list.component.html
- src/UI/Buyer/src/app/product/containers/product-list/product-list.component.ts
- src/UI/Buyer/src/app/shared/components/line-item-card/line-item-card.component.spec.ts
- src/UI/Buyer/src/app/shared/components/no-results/no-results.component.html
- src/UI/Buyer/src/app/shared/components/no-results/no-results.component.scss
- src/UI/Buyer/src/app/shared/components/no-results/no-results.component.spec.ts
- src/UI/Buyer/src/app/shared/components/no-results/no-results.component.ts
- src/UI/Buyer/src/app/shared/shared.module.ts
- Create shared component for no results. Add component to product list and product detail view
For Reference #228, #229
> #228, #229 - shared no results component
